algo = input('Escreva algo: ')
print('O tipo primitivo deste valor é: ',type(algo))
print('Só tem espaços?',algo.isspace() )
print('É numérico? ',algo.isnumeric())
print('É alfabético? ',algo.isalpha())
print('É alfanumérico? ',algo.isalnum())
print('É maiúsculo? ',algo.isupper())
print('É minúsculo? ',algo.islower())
print('Esta capitalizado? ',algo.capitalize())